### PR TITLE
Always write the update output file, even on container failure

### PR DESCRIPTION
**Pull request by rhyskoedijk**
If there are successful update outputs, it would be useful if Dependabot wrote them to the output file so that the caller can process them, even if the overall update process encountered errors.

This was encountered when testing https://github.com/dependabot/dependabot-core/issues/10834 and also in the tinglesoftware/dependabot-azure-devops implementation of Dependabot for Azure DevOps, see https://github.com/tinglesoftware/dependabot-azure-devops/issues/1407#issuecomment-2419304279.

When this happens...

```log
updater | +------------------------------------------------------------------------------------------------------------------------------------+
updater | |                                                Changes to Dependabot Pull Requests                                                 |
updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
updater | | created | Microsoft.Extensions.DependencyInjection ( from 8.0.0 to 8.0.1 ), Microsoft.Extensions.Logging ( from 8.0.0 to 8.0.1 ... |
updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +-----------------------------------------------------------------+
updater | |                  Dependencies failed to update                  |
updater | +-------------------------------------------+---------------------+
updater | | Microsoft.Extensions.Logging.Abstractions | update_not_possible |
updater | +-------------------------------------------+---------------------+
```

The "create_pull_request" output for the successful update could still be processed by the caller, if CLI wrote the output file.
After this change, the outputs from a partially successful Dependabot update can still be processed whilst also still reporting that the overall update failed.

### CODE REVIEW

**Comment by rhyskoedijk** [comment]
@jakecoffman @JamieMagee @brettfo sorry to ping you directly, but I've noticed you're active here recently; Is there any chance this PR would be considered? I'm facing a roadblock due to https://github.com/dependabot/dependabot-core/issues/10834 and this change would really help keep the PRs flowing.

**Comment by brettfo** [comment]
> ...sorry to ping you directly...

Don't be sorry, this is exactly why we're getting paid.

As for the change, I'm good with it and it makes sense from my perspective, but I mostly focus on the NuGet updater, so I'll yield to @jakecoffman on this one.

**Review by brettfo — APPROVED** [review]

**Comment by JamieMagee** [comment]
We'll likely not be able to merge until later this week, or early next week. We're pausing while GitHub Universe is on.

**Review by jakecoffman — APPROVED** [review]
This seems reasonable, thanks!

You might consider using the data from stdout or using `api-url` to get the HTTP requests directly from the Updater container. This will allow you to process the message immediately instead of waiting until the end, and avoids any kind of processing issues like the one this PR fixes.

**Comment by rhyskoedijk** [comment]
> You might consider using the data from stdout or using api-url to get the HTTP requests directly from the Updater container

Good idea, I will look in to this as an improvement. thanks for the help.

**Pull request merged**
